### ISSUE TITLE
FPS/lag (not optifabric issue)

### ISSUE THREAD

**Issue by theglotzerify** [Andrews54757/OptiFabric-updated#12]
breaking block animations and particle animations are chuggy / are running at low fps while the rest of the game runs smoothlyOptiFine_1.16.2_HD_U_G3_pre2 and fabric-carpet-1.16.2-1.4.9+v200815

**Comment by Andrews54757** [comment]
This is not an Optifabric issue. Please report to [Optifine](https://github.com/sp614x/optifine)

**Comment by theglotzerify** [comment]
it used to work in 1.16.1 with the optifabric back then. How can you be sure that its not a problem of the optifabric mod?

**Comment by Andrews54757** [comment]
Just as optifabric 1.16.1 is not the same as optifabric 1.16.2, optifine 1.16.2 is not the same as optifine 1.16.1.

Optifabric does not contain the optifine code itself, its sole job is to insert the optifine mod into the game (aka its like an installer).
