### ISSUE TITLE
I don't have any issues currently just wanted to thank you

### ISSUE THREAD

**Issue by Scorpion34** [Andrews54757/OptiFabric-updated#6]
I apologize for leaving this in the issue area but I just happened to stumble upon this and I really, really wanted to thank you truly I was so disappointed when modmuss50 ended this project so thank you so much please continue updating I love this mod and for future reference if I have any issues I'll be sure to report them thank you again 👍

**Comment by Andrews54757** [comment]
Thanks!

**Comment by iCaitlyn** [comment]
Thanks as well for continuing this mod!
